/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.jordantipton.kinesisexample.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TradeType {
  BUY, SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TradeType\",\"namespace\":\"com.jordantipton.kinesisexample.model\",\"symbols\":[\"BUY\",\"SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
